import { Heading, Text } from "@chakra-ui/react";
import Head from "next/head";
import {ShHeading} from "../components/typo";
import styles from "../styles/Home.module.css";

import "@fontsource/jetbrains-mono"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About PLC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading color="rgb(3,173,93)" fontFamily="JetBrains Mono, sans-serif">./plc</Heading>

      <ShHeading>about</ShHeading>
      <Text>Hello it is me, plc !</Text>
      <ShHeading>skills</ShHeading>
      <ShHeading>projects</ShHeading>
      {/* <ShHeading>work day routine?</ShHeading> */}
      <ShHeading>contact</ShHeading>
      {/* timeline on other page ? */}
      <ShHeading>timeline?</ShHeading>

    </div>
  );
}
