import { Heading, Text } from "@chakra-ui/react";
import "@fontsource/jetbrains-mono";
import Head from "next/head";
import { ShHeading } from "../components/typo";
import { Contact, Projects, Skills } from "../components/content";

const lorem = `
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin molestie posuere facilisis.
  Sed erat nulla, volutpat quis mollis vel, facilisis vitae sem. Pellentesque ac turpis eget mi elementum vestibulum vel at felis.
  Nunc molestie eleifend imperdiet. Aliquam erat volutpat. Sed sollicitudin tempus risus at rhoncus. Aenean rutrum mollis ipsum.
  Proin fermentum vulputate risus, at posuere turpis rhoncus et. In vulputate ex sit amet velit pellentesque sodales.
  Sed blandit massa nec tincidunt dignissim.
  `;

export default function Home() {
  return (
    <div style={{ padding: "0 2rem" }}>
      <Head>
        <title>About PLC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading
        fontSize="5em"
        color="rgb(3,173,93)"
        fontFamily="JetBrains Mono, sans-serif"
      >
        ~/plc
      </Heading>

      {/* <TypeEffect /> */}

      <ShHeading>about</ShHeading>
      <Text>Hello it is me, plc !</Text>
      <ShHeading>skills</ShHeading>
      <Skills />
      <ShHeading>projects</ShHeading>
      <Projects />
      <ShHeading>contact</ShHeading>
      <Contact />
    </div>
  );
}
